[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ["node_modules", "lib"]
remappings = [
    '@connext/=node_modules/@connext/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config